### ISSUE TITLE
Database Errors

### ISSUE THREAD

**Issue by Dosu333** [Dosu333/venueSheduling-API#2]
getting this error after migrations have being successful. Even after deleting the Department model

db_1   | 2020-10-07 14:45:37.696 UTC [33] STATEMENT:  ALTER TABLE "accounts_department" ALTER COLUMN "id" TYPE uuid USING "id"::uuid
api_1  |   Applying accounts.0006_auto_20201007_1120...Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
api_1  |     return self.cursor.execute(sql, params)
api_1  | psycopg2.errors.CannotCoerce: cannot cast type integer to uuid
api_1  | LINE 1: ...nts_department" ALTER COLUMN "id" TYPE uuid USING "id"::uuid
api_1  |                                                                  ^
api_1  | 
api_1  | 
api_1  | The above exception was the direct cause of the following exception:
api_1  | 
api_1  | Traceback (most recent call last):
api_1  |   File "manage.py", line 22, in <module>
api_1  |     main()
api_1  |   File "manage.py", line 18, in main
api_1  |     execute_from_command_line(sys.argv)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
api_1  |     utility.execute()
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
api_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
api_1  |     self.execute(*args, **cmd_options)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
api_1  |     output = self.handle(*args, **options)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
api_1  |     res = handle_func(*args, **kwargs)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
api_1  |     post_migrate_state = executor.migrate(
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
api_1  |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
api_1  |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
api_1  |     state = migration.apply(state, schema_editor)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
api_1  |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 236, in database_forwards
api_1  |     schema_editor.alter_field(from_model, from_field, to_field)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 571, in alter_field
api_1  |     self._alter_field(model, old_field, new_field, old_type, new_type,
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 166, in _alter_field
api_1  |     super()._alter_field(
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 721, in _alter_field
api_1  |     self.execute(
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
api_1  |     cursor.execute(sql, params)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
api_1  |     return super().execute(sql, params)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
api_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
api_1  |     return executor(sql, params, many, context)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
api_1  |     return self.cursor.execute(sql, params)
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
api_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
api_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
api_1  |     return self.cursor.execute(sql, params)
api_1  | django.db.utils.ProgrammingError: cannot cast type integer to uuid
api_1  | LINE 1: ...nts_department" ALTER COLUMN "id" TYPE uuid USING "id"::uuid
api_1  |                                                                  ^
api_1  | 
dev_api_1 exited with code 1

**Comment by Dosu333** [comment]
I had to delete migrations that contained the department model to fix this.
